import { AnimeKindType } from '@app/shared/types/shikimori/anime-kind.type';
import { AnimeRatingType } from '@app/shared/types/shikimori/queries/find-anime-query';
import { AnimeReleaseStatus } from '@app/shared/types/shikimori/user-anime-rate';
import { CharacterRoleGQL } from '@app/shared/types/shikimori/graphql/character-role.interface';
import { ExternalLinkGQL } from '@app/shared/types/shikimori/graphql/external-link.interface';
import { GenreGQL } from '@app/shared/types/shikimori/graphql/genre.interface';
import { IncompleteDateGQL } from '@app/shared/types/shikimori/graphql/incomplete-date.interface';
import { PersonRoleGQL } from '@app/shared/types/shikimori/graphql/person-role.interface';
import { PosterGQL } from '@app/shared/types/shikimori/graphql/poster.interface';
import { RelatedGQL } from '@app/shared/types/shikimori/graphql/related.interface';
import { ResourceIdType } from '@app/shared/types/resource-id.type';
import { ScoreStatGQL } from '@app/shared/types/shikimori/graphql/score-stat.interface';
import { ScreenshotGQL } from '@app/shared/types/shikimori/graphql/screenshot.interface';
import { StatusStatGQL } from '@app/shared/types/shikimori/graphql/status-stat.interface';
import { StudioGQL } from '@app/shared/types/shikimori/graphql/studio.interface';
import { TopicGQL } from '@app/shared/types/shikimori/graphql/topic.interface';
import { UserAnimeRateGQL } from '@app/shared/types/shikimori/graphql/user-anime-rate-gql.interface';
import { VideoGQL } from '@app/shared/types/shikimori/graphql/video.interface';

export interface AnimeGQL {
    airedOn: IncompleteDateGQL;
    characterRoles: CharacterRoleGQL;
    chronology: AnimeGQL[];
    createdAt: string;
    description: string;
    descriptionHtml: string;
    descriptionSource: string;
    duration: number;
    english: string;
    episodes: number;
    episodesAired: number;
    externalLinks: ExternalLinkGQL[];
    fandubbers: string[];
    fansubbers: string[];
    franchise: string;
    genres: GenreGQL[];
    id: ResourceIdType;
    isCensored: boolean;
    japanese: string;
    kind: AnimeKindType;
    licenseNameRu: string;
    licensors: string[];
    malId: ResourceIdType;
    name: string;
    nextEpisodeAt: string;
    opengraphImageUrl: string;
    origin: string;
    personRoles: PersonRoleGQL;
    poster: PosterGQL;
    rating: AnimeRatingType;
    related: RelatedGQL[];
    releasedOn: IncompleteDateGQL;
    russian: string;
    score: number;
    scoresStats: ScoreStatGQL;
    screenshots: ScreenshotGQL[];
    season: string;
    status: AnimeReleaseStatus;
    statusesStats: StatusStatGQL;
    studios: StudioGQL;
    synonyms: string[]
    topic: TopicGQL;
    updatedAt: string;
    url: string;
    userRate: UserAnimeRateGQL;
    videos: VideoGQL[];
}
