export const environment = {
  production: true,
  SHIKIVIDEOS_CLIENT_ID: process.env.SHIKIVIDEOS_CLIENT_ID,
  SHIKIVIDEOS_CLIENT_SECRET: process.env.SHIKIVIDEOS_CLIENT_SECRET,
  SHIKIMORI_CLIENT_ID: process.env.SHIKIMORI_CLIENT_ID,
  SHIKIMORI_CLIENT_SECRET: process.env.SHIKIMORI_CLIENT_SECRET,
  KODIK_TOKEN: process.env.KODIK_TOKEN,
  EPISODE_NOTIFICATION_TOKEN: process.env.EPISODE_NOTIFICATION_TOKEN
};
