export {
    chevronDown,
    chevronUp,
    closeOutline,
    filmOutline,
    languageOutline,
    libraryOutline,
    logInOutline,
    logOutOutline,
    notifications,
    openOutline,
    personCircle,
    personOutline,
    serverOutline,
    settingsOutline,
    trashOutline,
} from 'ionicons/icons';
