export {
    chevronDown,
    chevronUp,
    closeOutline,
    filmOutline,
    languageOutline,
    libraryOutline,
    logInOutline,
    logOutOutline,
    notifications,
    openOutline,
    personCircle,
    personOutline,
    serverOutline,
    settingsOutline,
    trashOutline,
    playBackOutline,
    playForwardOutline,
    send,
    checkmarkOutline,
    cloudUploadOutline,
    listOutline,
    resizeOutline,
    pencilOutline,
    ellipsisVerticalOutline,
    checkmarkDoneOutline,
    warningOutline,
} from 'ionicons/icons';
