name: "Code Quality Test: Build and Code style"

on:
    pull_request:
        branches:
            - v1.0.0

jobs:
  nodejs:
    runs-on: ubuntu-latest

    permissions:
      checks: write
      pull-requests: write
      contents: write

    name: PR CI
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Check code style
        run: npm run lint

      - name: Make .env
        uses: SpicyPizza/create-envfile@v2.0
        with:
            file_name: .env
            envkey_NODE_ENV: 'production'
            envkey_PLATFORM_TARGET: 'web-extension'
            envkey_KODIK_API_URI: ${{ secrets.KODIK_API_URI }}
            envkey_KODIK_AUTH_TOKEN: ${{ secrets.KODIK_AUTH_TOKEN }}
            envkey_SHIKIMORI_API_URI: ${{ secrets.SHIKIMORI_API_URI }}
            envkey_SHIKIMORI_CLIENT_ID: ${{ secrets.SHIKIMORI_CLIENT_ID }}
            envkey_SHIKIMORI_CLIENT_SECRET: ${{ secrets.SHIKIMORI_CLIENT_SECRET }}
            envkey_SHIKIMORI_EPISODE_NOTIFICATION_TOKEN: ${{ secrets.SHIKIMORI_EPISODE_NOTIFICATION_TOKEN }}
            envkey_SMARTHARD_API_URI: ${{ secrets.SMARTHARD_API_URI }}
            envkey_SMARTHARD_CLIENT_ID: ${{ secrets.SMARTHARD_CLIENT_ID }}
            envkey_SMARTHARD_CLIENT_SECRET: ${{ secrets.SMARTHARD_CLIENT_SECRET }}

      - name: Generate Angular Environment
        run: npm run set-env

      - name: Check build
        run: npm run build:prod
